### ISSUE TITLE
2022/3/1以降、らじるらじるの録音が失敗しているようです。

### ISSUE THREAD

**Issue by hisshihit** [uru2/radish#2]
radi.shをcron仕掛けて快適に録音させていただいておりましたm(_|_)m
が、2022/3/1以降、録音されていないことに気がつきました。

コマンドラインで実行させると
% ./radi.sh -t nhk -s tokyo-fm -d 10 -o ./dada.m4a
https://nhkradioakfm-i.akamaihd.net/hls/live/512290/1-fm/1-fm-01.m3u8: Server returned 404 Not Found
Record failed
てな感じです。

どのように動いているのかあまり理解できていないので調査中ですが、まずはご報告です。

**Comment by WhiteAnthrax** [comment]
らじるで今月(2月)28日未明に5.7.9以下のバージョンでは同時配信が聴けなくなったようなので、
radi.shの config_v5.?.?_radiru_and.xml を 5.8.1 とすると良さそうですね。

[493d7890df63a6bbf3f15970e5b753c97367a7ff](https://github.com/uru2/radish/commit/493d7890df63a6bbf3f15970e5b753c97367a7ff) で対応されてますね

**Comment by hisshihit** [comment]
ありがとうございました。
元のスクリプトをちょっといじっていたので、手patchで無事録音できるようになりました。
